services:
    # image project
    app-modelo:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app-modelo
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - modelo

    # nginx
    nginx-modelo:
        image: nginx:alpine
        container_name: nginx-modelo
        restart: unless-stopped
        ports:
            - "81:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - modelo

    # db mysql
    db-modelo:
        image: mysql:8
        container_name: db-modelo
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - volume-modelo:/var/lib/mysql
        ports:
            - "3389:3306"
        networks:
            - modelo

        # PHPMyAdmin
    phpmyadmin-modelo:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-modelo
        platform: linux/x86_64
        restart: unless-stopped
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db-modelo
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            UPLOAD_LIMIT: 300M
        networks:
            - modelo

volumes:
  volume-modelo:

networks:
    modelo:
        driver: bridge